spring:
  main:
    allow-bean-definition-overriding: true
  #Redis服务器IP
  redis:
    host: 49.234.51.235
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码
    password: lcy712
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #    driverClassName: com.mysql.cj.jdbc.Driver (Mysql8配置)
    url: jdbc:mysql://localhost:3306/helper?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wodeweilai2024YYD*




